---
secretStore:
  name: vault-backend
  kind: ClusterSecretStore

configdemosecret:
  key: secret/data/global/config-demo

global:
  hubClusterDomain: hub.example.com
  localClusterDomain: region-one.example.com

clusterGroup:
  isHubCluster: true

namespaces:
  lab-kafka

subscriptions:
  amq-streams:
    name: amq-streams
    namespace: lab-kafka

